version: '3.7'

services:
  registry:
    image: registry:2.7.1
    hostname: registry
    container_name: registry
    restart: always
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    networks:
      - registry
    volumes:
      - /data/registry:/var/lib/registry
      - ./certs:/certs
    ports:
      - 80:5000
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'

networks:
  registry:
    driver: bridge
