version: '2'
services:
  onlyoffice-documentserver:
    #build:
    #  context: .
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-rabbitmq
    environment:
      - DB_TYPE=postgres
      - DB_HOST=onlyoffice-postgresql
      - DB_PORT=5432
      - DB_NAME=onlyoffice
      - DB_USER=onlyoffice
      - AMQP_URI=amqp://guest:guest@onlyoffice-rabbitmq
      # Uncomment strings below to enable the JSON Web Token validation.
      #- JWT_ENABLED=true
      #- JWT_SECRET=secret
      #- JWT_HEADER=Authorization
      #- JWT_IN_BODY=true
    ports:
      - '80:80'
      - '443:443'
    stdin_open: true
    restart: always
    volumes:
       - /data/onlyoffice/data:/var/www/onlyoffice/Data
       - /data/onlyoffice/logs:/var/log/onlyoffice
       - /data/onlyoffice/cache:/var/lib/onlyoffice/documentserver/App_Data/cache/files
       - /data/onlyoffice/public:/var/www/onlyoffice/documentserver-example/public/files
       - /data/onlyoffice/fonts:/usr/share/fonts
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
       
  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB=onlyoffice
      - POSTGRES_USER=onlyoffice
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    expose:
      - '5432'
    volumes:
      - /data/pgsql:/var/lib/postgresql
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
  
