---
version: '3.7'

services:
  cerebro:
    hostname: cerebro
    container_name: cerebro
    image: lmenezes/cerebro:0.9.3
    restart: always
    networks:
      - cerebro
    restart: always
    ports:
      - 9000:9000
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'

networks:
  cerebro:
    external: true
