---
version: '3.7'

services:
  kafka-ui:
    container_name: kafka-ui
    #image: provectuslabs/kafka-ui:v0.7.1
    image: provectuslabs/kafka-ui:master
    restart: always
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./config.yaml:/etc/kafkaui/dynamic_config.yaml
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'
