---
version: "3"

services:
  gitlab:
    image: 'gitlab/gitlab-ce:12.1.6-ce.0'
    container_name: gitlab
    hostname: gitlab.3day.top
    restart: always

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # ##### for http
        external_url 'http://gitlab.3day.top:8081'
        # ####### for ssh
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        # ##### for https
        #external_url 'https://gitlab.3day.top'
        #nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.3day.top.pem"
        #nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.3day.top.key"
        #nginx['redirect_http_to_https'] = true
        #nginx['redirect_http_to_https_port'] = 80
        
        nginx['enable'] = true
        nginx['listen_port'] = 80
        #registry['enable'] = true
        #registry_external_url 'http://gitlab.3day.top:8081'
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        # email setting
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.qiye.aliyun.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "server@3day.top"
        gitlab_rails['smtp_password'] = "Q3BxX58YLshs2L"
        gitlab_rails['smtp_domain'] = "smtp.qiye.aliyun.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
        gitlab_rails['gitlab_email_from'] = 'server@3day.top'
    ports:
      - '8081:80'
      - '8443:443'
      - '8022:22'
    volumes:
      - '/data/config:/etc/gitlab'
      - '/data/logs:/var/log/gitlab'
      - '/data/data:/var/opt/gitlab'
      #- './ssl:/etc/gitlab/ssl'
      - '/etc/localtime:/etc/localtime:ro'
    networks:
      - gitlab
    logging:
      driver: json-file
      options:
        max-file: '3'
        max-size: '10m'

networks:
  gitlab:
    external: true



